# Phyton Matrix

References:  
https://www.tutorialspoint.com/numpy/numpy_matrix_library.htm  
https://numpy.org/devdocs/user/numpy-for-matlab-users.html#array-or-matrix-which-should-i-use  
Note: To make a new line in markdown add two spaces after the first sentence

In [1]:
import numpy as np
import numpy.matlib as npm #Submodules are not imported automatically
import numpy.linalg as npalg #Linear algebra

Matrix objects follows matrix matematical rules by default

Arrays are use more often than matices in programming.

In [2]:
print('Empty Matrix:\n' ,npm.empty((2,2), dtype = 'float64')) 

print('\nZeroes Matrix:\n',npm.zeros((2,2)))

print('\nOnes Matrix:\n',npm.ones((2,2)))

Empty Matrix:
 [[1.24766850e-311 1.14425908e+243]
 [7.45717380e+006 3.38226911e-061]]

Zeroes Matrix:
 [[0. 0.]
 [0. 0.]]

Ones Matrix:
 [[1. 1.]
 [1. 1.]]


In [3]:
print('Identity Matrix:\n',npm.identity(3, dtype = 'int16')) #Always a square matrix

print('\nEye Matrix: \n', npm.eye(3, 4 ,0, dtype = 'int8')) #Does not need to be square

print('\nEye Matrix: \n', npm.eye(3, 6 ,2, dtype = 'int8')) #Does not need to be square


Identity Matrix:
 [[1 0 0]
 [0 1 0]
 [0 0 1]]

Eye Matrix: 
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]

Eye Matrix: 
 [[0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]]


In [2]:
#Transpose. Same for arrays and matrices

A = npm.matrix([[1, 2, 3],[4, 5, 6], [7, 8, 9], [10, 11, 12]])
print('A:\n', A)
print('Transpose:\n',A.T) #Matrix transpose

A = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9], [10, 11, 12]])

print('\nA:\n', A)
print('Transpose:\n',A.T) #Matrix transpose

A:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Transpose:
 [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]

A:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Transpose:
 [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [7]:
#Random matrix
print(npm.rand(4,4))

[[0.50898519 0.90082904 0.51706811 0.84088642]
 [0.86648828 0.93878032 0.24874753 0.89749455]
 [0.44816882 0.89481716 0.48485063 0.20785547]
 [0.01411936 0.85990353 0.32259117 0.38753144]]


In [21]:
#Matrix multiplication

A = npm.matrix([[4, 3], [2, 1]]) 
B = npm.matrix('1, 2; 3, 4') #Both formats are equivalent

print('A:\n', A)
print('B:\n', B)
print('A*B:\n',A*B)

A:
 [[4 3]
 [2 1]]
B:
 [[1 2]
 [3 4]]
A*B:
 [[13 20]
 [ 5  8]]


In [42]:
A = np.array([[4, 3], [2, 1]]) 
#B = np.array('1, 2; 3, 4') #Does not work in arrays
B = np.array([[1,2],[3,4]])

print('A:\n', A)
print('B:\n', B)
print('\nA*B:\n',A*B)
print('\ndot(A,B):\n', np.dot(A,B))
print('\nA@B:\n',A@B) #@Is the equivalent of matrix multiplication

A:
 [[4 3]
 [2 1]]
B:
 [[1 2]
 [3 4]]

A*B:
 [[4 6]
 [6 4]]

inner(A,B):
 [[10 24]
 [ 4 10]]

dot(A,B):
 [[13 20]
 [ 5  8]]

A@B:
 [[13 20]
 [ 5  8]]


In [51]:
#Inner product: Tricky

A = np.array([[4, 3], [2, 1]]) 
B = np.array([[1,2],[3,4]])

print('A:\n', A)
print('B:\n', B)
print('\nInner(A,B):\n', np.inner(A,B))

#Notice: 
print('\n',4*1+3*2, 4*3+3*4)
print('\n',2*1+1*2, 2*3+1*4)
  

A:
 [[4 3]
 [2 1]]
B:
 [[1 2]
 [3 4]]

Inner(A,B):
 [[10 24]
 [ 4 10]]

 10 24

 4 10


In [53]:
#Outer product:

A = np.array([[4, 3], [2, 1]]) 
B = np.array([[1,2],[3,4]])

print('A:\n', A)
print('B:\n', B)
print('\nOuter(A,B):\n', np.outer(A,B))

A:
 [[4 3]
 [2 1]]
B:
 [[1 2]
 [3 4]]

Outer(A,B):
 [[ 4  8 12 16]
 [ 3  6  9 12]
 [ 2  4  6  8]
 [ 1  2  3  4]]


In [77]:
#Determinant

A = np.array([[4, 3], [2, 1]])

print('A:\n', A)

print('\n|A|:', npalg.det(A))

B = np.array([[1, 3], [3, 9]])
print('\nB:\n', B)
print('\n|B|:', npalg.det(B))

A:
 [[4 3]
 [2 1]]

|A|: -2.0

B:
 [[1 3]
 [3 9]]

|B|: -4.996003610813175e-16

C:
 [[0.3235723  0.10229923 0.00679825 ... 0.48080788 0.37322587 0.43343096]
 [0.08614292 0.78759584 0.99751077 ... 0.16401257 0.26154838 0.53263207]
 [0.06928653 0.80771399 0.29335895 ... 0.54115783 0.76796186 0.26942361]
 ...
 [0.24434256 0.99876482 0.24940374 ... 0.3254425  0.24476605 0.92082733]
 [0.45566683 0.05560448 0.817796   ... 0.80565505 0.77174588 0.36534119]
 [0.02574196 0.66264626 0.81049167 ... 0.83530854 0.97607608 0.5412466 ]]

|C|: 4.388174280989307e+25


In [93]:
#Determinant
C = np.random.randint(10, size = (250,250))

print('C:\n', C)
print('\n|C|:', npalg.det(C))

C = C/10 #Scaling  c

print('C:\n', C)
print('\n|C|:', npalg.det(C))


C:
 [[3 0 5 ... 7 3 3]
 [5 0 6 ... 5 9 0]
 [9 4 5 ... 6 5 5]
 ...
 [8 3 3 ... 5 3 0]
 [0 9 5 ... 5 2 1]
 [0 6 8 ... 9 9 5]]

|C|: -inf
C:
 [[0.3 0.  0.5 ... 0.7 0.3 0.3]
 [0.5 0.  0.6 ... 0.5 0.9 0. ]
 [0.9 0.4 0.5 ... 0.6 0.5 0.5]
 ...
 [0.8 0.3 0.3 ... 0.5 0.3 0. ]
 [0.  0.9 0.5 ... 0.5 0.2 0.1]
 [0.  0.6 0.8 ... 0.9 0.9 0.5]]

|C|: -1.3460856719457858e+112


In [ ]:
#Determinant
C = np.random.randint(10, size = (20000,20000))

print('C:\n', C)
print('\n|C|:', npalg.det(C))
print('\ninv(C):', npalg.inv(C))


C:
 [[7 5 0 ... 3 0 2]
 [3 4 6 ... 7 6 9]
 [9 7 5 ... 8 8 5]
 ...
 [0 0 1 ... 9 8 8]
 [2 7 2 ... 3 3 0]
 [4 4 3 ... 2 5 2]]


In [20]:
#Investment
A = np.array([[1, 2, 3], [8, 2, 1], [4, 1, 11]])

print('A:\n',A )
print('\n|A|:', npalg.det(A))

B = npalg.inv(A)   #Inverse Matrix

print('\ninv(A):\n', B)

print('\nA@B:\n', A@B)
      

A:
 [[ 1  2  3]
 [ 8  2  1]
 [ 4  1 11]]

|A|: -146.99999999999997

inv(A):
 [[-0.14285714  0.1292517   0.02721088]
 [ 0.57142857  0.00680272 -0.15646259]
 [ 0.         -0.04761905  0.0952381 ]]

A@B:
 [[1.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00]
 [0.00000000e+00 5.55111512e-17 1.00000000e+00]]


In [19]:
#Inverse
A = np.array([[1, 2, 3], [8, 2, 1], [9, 4, 4]])

print('A:\n',A )
print('\n|A|:', npalg.det(A))

B = npalg.inv(A)

print('\ninv(A):\n', B)

print('\nA@B:\n', A@B)

#Notice that matrices without inverse can be problematic
      

A:
 [[1 2 3]
 [8 2 1]
 [9 4 4]]

|A|: -3.972131265881095e-15

inv(A):
 [[-0.08951867  0.11021143  0.02069276]
 [ 0.09806568 -0.05038237  0.04768331]
 [ 0.18668466 -0.11426001  0.07242465]]

A@B:
 [[ 0.66666667 -0.33333333  0.33333333]
 [-0.33333333  0.66666667  0.33333333]
 [ 0.33333333  0.33333333  0.66666667]]


In [25]:
#Pseudo Inverse
A = np.array([[1, 2, 3], [8, 2, 1], [9, 4, 4]])

print('A:\n',A )
print('\n|A|:', npalg.det(A))

B = npalg.inv(A)   #Inverse Matrix
C = npalg.pinv(A)  #Pseudo inverse Matrix

print('\ninv(A):\n', B)
print('\npinv(A):\n', C)

print('\nA@C:\n', A@C)

A:
 [[1 2 3]
 [8 2 1]
 [9 4 4]]

|A|: -3.972131265881095e-15

inv(A):
 [[-1.00701607e+15 -1.00701607e+15  1.00701607e+15]
 [ 5.79034238e+15  5.79034238e+15 -5.79034238e+15]
 [-3.52455623e+15 -3.52455623e+15  3.52455623e+15]]

pinv(A):
 [[-0.08951867  0.11021143  0.02069276]
 [ 0.09806568 -0.05038237  0.04768331]
 [ 0.18668466 -0.11426001  0.07242465]]

A@C:
 [[ 0.66666667 -0.33333333  0.33333333]
 [-0.33333333  0.66666667  0.33333333]
 [ 0.33333333  0.33333333  0.66666667]]


In [27]:
#Pseudo inverse
A = np.array([[1, 2, 3, 4], [8, 2, 1, 5], [9, 4, 4, 2]])

print('A:\n',A )
#print('\n|A|:', npalg.det(A))

#B = npalg.inv(A)   #Inverse Matrix
C = npalg.pinv(A)  #Pseudo inverse Matrix

#print('\ninv(A):\n', B)
print('\npinv(A):\n', C)

print('\nA@C:\n', A@C)

A:
 [[1 2 3 4]
 [8 2 1 5]
 [9 4 4 2]]

pinv(A):
 [[-0.12299981  0.07673029  0.0541739 ]
 [ 0.06439175 -0.08405629  0.08135724]
 [ 0.14092925 -0.16001542  0.11818007]
 [ 0.14285714  0.14285714 -0.14285714]]

A@C:
 [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 6.66133815e-16  1.00000000e+00  4.44089210e-16]
 [ 1.11022302e-16 -1.11022302e-16  1.00000000e+00]]
